'use client';

/**
 * Phase 2 — 3D Cabin Viewport, asset + lighting + controls.
 *
 * Mounts an R3F <Canvas> with an isometric bird's-eye perspective camera,
 * "premium airline" lighting (warm overhead + soft blue rim from the
 * window-line LEDs), and the prebuilt cabin glTF asset at
 * /3d/whole_cabin.glb (generated by scripts/build-cabin-glb.mjs).
 *
 * OrbitControls are deliberately constrained:
 *   - polar angle clamped (PI/4 … PI/2.2) so the user can orbit the
 *     sides + look top-down but never under the cabin floor
 *   - distance clamped (5 … 40) so the camera neither pierces the hull
 *     nor floats so far that the plane disappears
 *   - panning disabled — the cabin always stays centred, so two-finger
 *     drags / right-click drags can't push the plane off-screen
 *
 * Interactivity (seat clicks, HUD, status materials) lands in Phase 3.
 */

import { Suspense } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, useGLTF, Html } from '@react-three/drei';

const CABIN_GLB_PATH = '/3d/whole_cabin.glb';

function CabinModel() {
  const gltf = useGLTF(CABIN_GLB_PATH);
  return <primitive object={gltf.scene} />;
}

useGLTF.preload(CABIN_GLB_PATH);

function CanvasLoading() {
  return (
    <Html center>
      <p className="text-sm font-medium text-white animate-pulse select-none">
        3D Cabin Loading…
      </p>
    </Html>
  );
}

export default function ThreeCabinViewport() {
  return (
    <div className="w-full h-[600px] bg-slate-950 relative rounded-xl overflow-hidden">
      <Canvas
        shadows
        dpr={[1, 2]}
        camera={{ position: [15, 15, 20], fov: 45, near: 0.1, far: 200 }}
      >
        <ambientLight intensity={0.6} />
        <directionalLight
          position={[10, 20, 10]}
          intensity={1.2}
          castShadow
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
        />
        <pointLight position={[-8, 1.5, 0]} intensity={0.45} color="#3FA9FF" distance={28} decay={2} />
        <pointLight position={[8, 1.5, 0]} intensity={0.45} color="#3FA9FF" distance={28} decay={2} />

        <Suspense fallback={<CanvasLoading />}>
          <CabinModel />
        </Suspense>

        <OrbitControls
          makeDefault
          enableDamping
          dampingFactor={0.12}
          enablePan={false}
          minPolarAngle={Math.PI / 4}
          maxPolarAngle={Math.PI / 2.2}
          minDistance={5}
          maxDistance={40}
          rotateSpeed={0.7}
          zoomSpeed={0.8}
        />
      </Canvas>
    </div>
  );
}
